#!/bin/bash

# Location where the CAPTURE framework was installed.
cap_install_fullpath=$(command -v cap)
CAP_INSTALL_PATH=$(dirname "$cap_install_fullpath")

# Load commands
for file in "$CAP_INSTALL_PATH"/commands/*.sh; do
    source "$file"
done

# Check if a parameter was provided
if [ "$#" -eq 0 ]; then
    cap_help
    exit 1
fi

# Retrieve the function name from the first parameter
function_name="$1"
namespaced_name="cap_$function_name"

# Check if the function exists
if declare -f "$namespaced_name" > /dev/null; then
    # Extract parameters starting from the 2nd one
    params=("${@:2}")

    # Call the function with the extracted parameters
    $namespaced_name "${params[@]}"
else
    echo "Unknown command: $function_name"
    echo "Usage: $0 {md5|sha256}"
    exit 1
fi
